{
  "services": [
    "docker"
  ],
  "sudo": "required",
  "before_install": [
    "openssl aes-256-cbc -K $encrypted_d303290e7d32_key -iv $encrypted_d303290e7d32_iv -in keys/id_rsa_observatory_extension.key.enc -out keys/id_rsa_observatory_extension.key -d"
  ],
  "before_script": "cp .env.sample .env",
  "script": [
    #"make etl-unittest",
    "GIT_SSH_COMMAND='ssh -i keys/id_rsa_observatory_extension.key' git clone git@github.com:cartodb/observatory-extension",
    "make extension-unittest"
  ]
}

