services:
 - docker
sudo: required
#before_install:
#  - echo -e "machine github.com\n  login $token" >> ~/.netrc
before_script:
  - cp .env.sample .env
script:
  #- make etl-unittest
  - git clone "https://$token@github.com/cartodb/observatory-extension.git"
  - make extension-unittest
env:
  global:
    - secure: XM1tV+l1MRaFRRHJiU5B68lntZKZgNyF/SV2r53ccShuTDNDPDDIQAme8m2Q7nM6uhEWjJWXiaFKv4LWye/YaOZUhU3He+PMwhxXqqey5h9mgjV8i1gUdCU398GE53CK+Yp+TYwrL0QUvBWXb57Zs2icisEIyDIqNidBEoVM2l0W7NpLZiZazB5uf8H+OpVag/nwTb18kT3L1LWVSXc6H9GFWdJaxwAVMKhp1FC9XvBtNfLGrvmP7pOJa5GFv1Y0lIuLazDPewQkBANUcfDnqxORWkR8M1KOAB8yf4xG0ZFma+w2HK11tEft23gTr+vWSvn0ssxFMZQFHo2GdH6HhphtVeRd+alLThHqALbAtvpxwjQlxtPY04we9kj/vroUPhkNEuKHByHde0Ru4DtWaqS0hiwnYUnaZA1oXNt0UTRlad3MLpVBVX1AnYUsqQT1uA28UnJ19n778Rblj/9lJ8vbw/4aNasp7wsZbojz9YO88hlg+ixKR5Z7W5zQigDg4ur1dsJ+x8AIH+iM9KJtNthZfWUpuI2wG6x204UvNbbsHaoQdRkwg4/ti5jxwhyI8eiZKsXX+vE+rXaqMUOztOI/p9gNOujPej3Z7CADS2EMkGKmPrem+Rk8vpL92Ie1WzyTCzq8pB6xpMCIorFW1XM2GGAMtNDEGyaA6D/HvnY=
