# Thanks to
# https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml
{
  "postgres": {
    "build": "postgres",
    "volumes": [
      "./postgres/postgresql.conf:/etc/postgresql/9.4/main/postgresql.conf",
      "./postgres/data:/var/lib/postgresql"  # commented to work on mac --
                                              # will cause persistence issues!!
    ],
    "ports": [
      "5432:5432"
    ],
    "privileged": true
  },
  "browser": {
    "image": "nginx:latest",
    "volumes": [
      "./browser:/usr/share/nginx/html/browser/:ro",
      "./browser/nginx.conf:/etc/nginx/conf.d/default.conf:ro",
      "./catalog/build/html:/usr/share/nginx/html/catalog/:ro"
    ],
   "ports": [
      "80:80"
   ]
  },
  "bigmetadata_daemon": {
    #"build": ".",
    "image": "recessionporn/bigmetadata:docker-hub",
    "links": [
      "postgres"
    ],
    "volumes": [
      ".:/bigmetadata"
    ],
    "ports": [
      "8082:8082"
    ],
    "environment": {
      "PYTHONPATH": "/bigmetadata",
      "PGHOST": "postgres",
      "PGUSER": "docker",
      "PGPASSWORD": "docker",
      "PGDATABASE": "gis"
    },
    "env_file": ".env"
  },
  "bigmetadata": {
    "image": "recessionporn/bigmetadata:docker-hub",
    "links": [
      "bigmetadata_daemon",
      "postgres"
    ],
    "volumes": [
      ".:/bigmetadata"
    ],
    "environment": {
      "PYTHONPATH": "/bigmetadata",
      "PGHOST": "postgres",
      "PGUSER": "docker",
      "PGPASSWORD": "docker",
      "PGDATABASE": "gis"
    },
    "env_file": ".env"
  },
  "ipython": {
    "build": "ipython",
    "ports": [
      "8888:8888"
    ],
    "links": [
      "postgres"
    ],
    "volumes": [
      ".:/bigmetadata"
    ],
    "working_dir": "/tmp/ipython",
    "command": "sh -c /bigmetadata/ipython/start.sh"
  },
}
